# syntax highlighter
highlighter: pygments

# sass
sass:
  sass_dir:  _sass
  style:     compressed

# segment config
segments:
  letters:
    - DP
    - G
    - F
    - E
    - D
    - C
    - B
    - A
  colours:
    - green
    - blue
    - purple
    - red
    - orange
    - yellow
